import sys
import os
sys.path.append(os.getcwd())

### WARNING: the working directory must be the root of the project

import numpy as np
from numpy.linalg import norm
import visualizer3d_vbo as vbo
import galaxy_generator as gg

gravity_constant= 1.560339E-13

class Body() :
    """ A class to simulate a body of a galaxy."""

    def __init__(self, mass, color, position, velocity):
        """A constructor.
        
        Args:
            mass: the mass of the body
            color: the colore of the body
            position: the position vector of the body
            velocity: thhe velocity vector of the body

        Return: 
            None
        """

        self.mass=mass
        self.color=color
        self.position=position
        self.velocity=velocity

    def update(self, delta_t, acceleration):
        """A function updating the position and the velocity
        of the vector given a certain acceleration and time step.
        
        Args:
            delta_t: the time step
            acceleration: the acceleration of the body
        
        Return: 
            None
        """

        self.position=self.position + delta_t*self.velocity + 1/2*(delta_t**2)*acceleration
        self.velocity=self.velocity + delta_t*acceleration

    def distance(self, other):
        """A function computing the distance between this body and another othe
        
        Args:
            other: the other body

        Return: 
            None
        """
        return np.norm(self.position-other.position,2)

class NBodies():
    
    def __init__(self, data_file_name):
        """Construct the bodies from a txt generated by galaxy_generator.py.
        
        Args:
            data_file_name: the string containing the name of the data file
        """

        data= np.loadtxt(data_file_name, dtype=np.double)
        bodies_list=[]
        for i in range(data.shape[0]):
                mass=data[i,0]
                color=gg.generate_star_color(mass)
                position=np.array([data[i,1],data[i,2],data[i,3]])
                velocity=np.array([data[i,4],data[i,5],data[i,6]])
                new_corps= Body(mass,color,position,velocity)
                bodies_list.append(new_corps)
        self.bodies_list= bodies_list

    def gravity(self, idx_caller):
        """A function computing the gravity exerted on a given body 
        by all the other ones.
        
        Args:
            idx_caller: the index of the corresponding body in self.bodies_list

        Return: 
            None
        """

        gravity=np.zeros(3)
        for i in range(len(self. bodies_list)):
            caller=self. bodies_list[idx_caller]
            if i==idx_caller:
                pass
            else:
                current=self. bodies_list[i]
                dist_vec=current.position-caller.position
                gravity+=caller.mass*current.mass*dist_vec/(norm(dist_vec,2)**3)
        return gravity_constant*gravity

    def get_points(self):
        """A function computing the arrays of positions of all bodies.
        
        Args:
            None

        Return: 
            points: the corresponding array
        """

        bodies_list=self.bodies_list
        number_of_body=len(bodies_list)
        
        points=np.zeros((number_of_body,3))
        for i,body in enumerate(bodies_list):
            points[i,:] = body.position
        return points
        
    def update(self, delta_t):
        """A function updating the position and the velocity
        of the vector given a certain time step, the acceleration
        being deduced from gravitationnal attraction.
        
        Args:
            delta_t: the time step
        
        Return: 
            None
        """

        acceleration=np.zeros((len(self.bodies_list),3))
        for i,body in enumerate(self.bodies_list):
            acceleration[i,:]=self.gravity(i)/body.mass
        for i,body in enumerate(self.bodies_list):
            body.update(delta_t,acceleration[i,:])
        return self.get_points()


## Tests

ncorps=NBodies("Alexandre/1000_bodies")

delta_t=0.001

def test(ncorps, delta_t): 
    """
    A function to test the naive N-bodies simulation 
    
    Args:
        ncorps: the NBody object containing the bodies to be studied
        delta_t: the time step of the study

    Return: 
        None
    """

    bodies_list=ncorps.bodies_list
    number_of_body=len(bodies_list)
    
    points=np.zeros((number_of_body,3))
    for i,body in enumerate(bodies_list):
        points[i,:] = body.position
   
    # Génération de couleurs aléatoires
    colors = np.array([body.color for body in bodies_list])
    
    # Génération de luminosités aléatoires
    luminosities = np.ones(number_of_body).astype(np.float32)
    
    # Définition des limites de l'espace
    bounds = ((-100, 100), (-100, 100), (-100, 100))
    
    # Création et lancement du visualiseur

    visualizer = vbo.Visualizer3D(points, colors, luminosities, bounds)
    visualizer.run(ncorps.update, delta_t)

if __name__ == '__main__':
    test(ncorps, delta_t)